In [1]:
# this creates two csv files containing the Covid-19 cases (and deaths) worldwide for each country.
import pandas as pd
import numpy as np




# url to the data 'Novel Coronavirus (COVID-19) Cases', provided by JHU CSSE
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/'

# confirmed cases worldwide for each country
cases = pd.read_csv(url + 'time_series_covid19_confirmed_global.csv')
deaths = pd.read_csv(url + 'time_series_covid19_deaths_global.csv')

cases = cases.groupby('Country/Region', axis=0).sum()  # here we sum over Province/State for countries (US=Alabama, Alaska,..)
deaths = deaths.groupby('Country/Region', axis=0).sum()

# Some cleaning of the data:
last_day = cases.columns[-1]
cases.sort_values(
    [last_day], ascending=False, axis=0,
    inplace=True)  # ordering them by total number at the latest data point
deaths = deaths.reindex(index=cases.index)  # same ordering as global_confirmed

cases.index.name = 'country'  # delte the name of the index
deaths.index.name = 'country'

# delete the following rows from the data
to_del = ['Diamond Princess', 'MS Zaandam', 'Holy See', 'Western Sahara']
cases = cases.drop(to_del)
deaths = deaths.drop(to_del)

#also del the Columns 'Lat' and 'Long'
cases.drop(['Lat','Long'],axis=1, inplace=True)
deaths.drop(['Lat','Long'],axis=1, inplace=True)

print('The data is from ' +
      str(pd.to_datetime(cases.columns[-1]).strftime('%d/%m/%Y')) + '.')


cases.to_csv('cases.csv')
deaths.to_csv('deaths.csv')
cases

The data is from 04/05/2020.

,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,4/25/20,4/26/20,4/27/20,4/28/20,4/29/20,4/30/20,5/1/20,5/2/20,5/3/20,5/4/20
country,,,,,,,,,,,,,,,,,,,,,
US,1,1,2,2,5,5,5,5,5,7,...,938154,965785,988197,1012582,1039909,1069424,1103461,1132539,1158040,1180375
Spain,0,0,0,0,0,0,0,0,0,0,...,205905,207634,209465,210773,212917,213435,213435,216582,217466,218011
Italy,0,0,0,0,0,0,0,0,0,2,...,195351,197675,199414,201505,203591,205463,207428,209328,210717,211938
United Kingdom,0,0,0,0,0,0,0,0,0,2,...,149569,154037,158348,162350,166441,172481,178685,183500,187842,191832
France,0,0,2,3,3,3,4,5,5,5,...,161644,162220,165963,169053,166543,167299,167305,168518,168925,169583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Suriname,0,0,0,0,0,0,0,0,0,0,...,10,10,10,10,10,10,10,10,10,10
Mauritania,0,0,0,0,0,0,0,0,0,0,...,7,7,7,7,8,8,8,8,8,8
Papua New Guinea,0,0,0,0,0,0,0,0,0,0,...,8,8,8,8,8,8,8,8,8,8
Bhutan,0,0,0,0,0,0,0,0,0,0,...,7,7,7,7,7,7,7,7,7,7
Comoros,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,3,3,3